Send uid from AM to metrica
yandexmobile/yandex-login-sdk-android pull request #9
Opened 2022-08-29 13:06 UTC by VinogradovAlexander

2022-08-30 12:50 UTC, avstaim requested changes

2022-08-30 12:50 UTC, avstaim commented on base-sample/build.gradle
> +        minSdk 15
15??

2022-08-30 12:50 UTC, avstaim commented on base-sample/proguard-rules.pro
> +# Add project specific ProGuard rules here.
давай уберем мусорные комменты

2022-08-30 12:50 UTC, avstaim commented on lib/src/main/java/com/yandex/authsdk/internal/MetricaInteractor.kt
> +            val clazz = Class.forName("com.yandex.metrica.p")
выглядит опасным - а если у хоста будет собственный прогард, который пообфусцирует метрику еще разок?

2022-08-31 08:58 UTC, VinogradovAlexander commented on lib/src/main/java/com/yandex/authsdk/internal/MetricaInteractor.kt
> +            val clazz = Class.forName("com.yandex.metrica.p")
Это код от ребят из метрики, по идее в либе правила должны быть, чтоб хост не обфусцировал "com.yandex.metrica". С какой то доп обфускацией мы все равно не можем ничего сделать, в крайнем случае просто не будем передавать uid

2022-08-31 14:54 UTC, VinogradovAlexander commented on base-sample/build.gradle
> +        minSdk 15
это от старого сэмпла) поднял до 21

2022-08-31 14:54 UTC, VinogradovAlexander commented on base-sample/proguard-rules.pro
> +# Add project specific ProGuard rules here.
удалил лишние файлы

2022-09-02 13:53 UTC, merged